### ISSUE TITLE
Dispatch on Mouse Input is dispatching when it shouldn't be

### ISSUE THREAD

**Issue by douglasZwick** [unity-lpk/DragonPack#17]
The LPK_DispatchOnMouseInput takes the liberty of dispatching its event on many occasions when it's not warranted. Specifically, on **line 203**, **line 217**, and **line 231**, there are **==** operators where there should be **!=** operators.

**To Reproduce**
1. Attach this component to something and set up its event. Keep the input mode set to **LEFT_BUTTON_PRESSED**.
2. Run the game and move the mouse onto the object. The event will repeatedly dispatch as long as the mouse is on the object.

**Expected behavior**
The event should only be dispatched when the mouse is clicked.

**Version(please complete the following information):**
The file seems to have been last updated on 9 October 2019.

**Comment by aeonwilliams** [comment]
Fixed! Thanks Doug.
