### ISSUE TITLE
ModifyTransformOnEvent tags are string fields instead of drop-downs

### ISSUE THREAD

**Issue by douglasZwick** [unity-lpk/DragonPack#19]
To be a valid bug report, and to receive prompt turn around time for solving this, you must fill out all sections not marked optional.

**Describe the bug**
The fields for specifying which tags to copy transform properties from are string fields, whereas most tag-specifying fields are drop-down lists.

**Version(please complete the following information):**
 - DragonPack Version: 2.0.22

**Comment by ghost** [comment]
Fixed for Spring 2020.
