### ISSUE TITLE
Object Display max objects is unintuitive

### ISSUE THREAD

**Issue by douglasZwick** [unity-lpk/DragonPack#22]
**Describe the bug**
The LPK_ObjectDisplay component is unreliable when its Max Display Objects property is smaller than the maximum value that its counter might reach.

**To Reproduce**
1. Create a counter with a **Value** of 8. (Make sure its max is at least 8.)
2. Create an ObjectDisplay with a **Max Display Objects** of 3.
3. Tell the counter to use that object display.
4. Run the game. The object display will be full, and the counter's value will be 8.
5. Cause the counter to go down by 3. The object display will now be empty, and the counter's value will be 5.
6. Cause the counter to go down by another 3. The object display will still be empty, and the counter's value will be 2.
7. Cause the counter to go up by 3. The object display will now be full, like it was at the start, but now the counter's value will be 5 instead of 8. The object display is thus unreliable.

**Expected behavior**
In the NES version of *Contra* (Konami, 1988), the hero's lives in reserve are represented during the game with little medal icons in the corner of the screen:
![image](https://user-images.githubusercontent.com/650318/71757170-9d4fd800-2e48-11ea-85c6-b7081d4dc057.png)
There is no max to the number of lives in reserve the hero can have, but the game will never show more than four medals:
![image](https://user-images.githubusercontent.com/650318/71756973-8361c580-2e47-11ea-9ef1-dbcc7050ab06.png)
This display is always perfectly accurate between 0 and 4 lives in reserve. This is how I think the Max Display Objects property should work; the object display should make no change as long as the value of its counter is at or above the max.

**Comment by ghost** [comment]
Good catch - fixed!
